# Generated by Django 5.2.7 on 2026-01-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('document', models.FileField(upload_to='applications/')),
                ('status', models.CharField(default='submitted', max_length=20)),
            ],
        ),
    ]
