# Generated by Django 5.2.7 on 2026-01-14 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('viewings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='viewing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='viewings.viewing'),
        ),
    ]
